"""numeraire — a research framework for empirical asset pricing.

The reference unit against which methods are measured. The spine (``numeraire.core``)
is method-agnostic and depended upon by everything; methods and adapters depend on it,
never the reverse (enforced by import-linter, see pyproject ``[tool.importlinter]``).
"""

from numeraire.core import capabilities
from numeraire.core.data import (
    CharBlock,
    CrossSectionView,
    FeatureBlock,
    PanelTensor,
    TimeSeriesView,
    VintagedBlock,
)
from numeraire.core.engine import (
    ForecastOutput,
    PanelWeightsOutput,
    PricingOutput,
    WeightsOutput,
    backtest,
    backtest_forecast,
    backtest_panel,
    backtest_pricing,
    backtest_pricing_in_sample,
    backtest_weights,
    config_hash,
    pricing_in_sample,
    walk_forward,
    walk_forward_forecast,
    walk_forward_panel,
    walk_forward_pricing,
)
from numeraire.core.evaluators import (
    AlphaEvaluator,
    AverageAbsAlphaEvaluator,
    CEQEvaluator,
    ClarkWestEvaluator,
    CrossSectionalR2Evaluator,
    ExposureEvaluator,
    ICEvaluator,
    InformationRatioEvaluator,
    M2Evaluator,
    MeanReturnEvaluator,
    OOSR2Evaluator,
    OutOfSampleR2Evaluator,
    SharpeEvaluator,
    SortinoEvaluator,
    SquaredErrorDiffEvaluator,
    StrategyReturnEvaluator,
    TreynorEvaluator,
)
from numeraire.core.protocols import (
    DataView,
    Estimator,
    Evaluator,
    Model,
    Splitter,
    SupportsForecast,
    SupportsPricing,
    SupportsWeights,
)
from numeraire.core.registry import (
    available_evaluators,
    get_evaluator,
    register_evaluator,
)
from numeraire.core.schema import RESULT_COLUMNS, validate_result
from numeraire.core.simulate import RebalanceSchedule, SimulationResult, simulate_weights
from numeraire.core.sorts import SortResult, make_sorts, sort_portfolios
from numeraire.core.splitter import WalkForwardSplitter, validation_split
from numeraire.core.stats import (
    adjust_pvalues,
    adjust_tests,
    alpha_regression,
    certainty_equivalent,
    clark_west,
    clark_west_test,
    fama_macbeth,
    grs_test,
    newey_west_lrv,
    performance_fee,
    return_loss,
    sharpe_diff_test,
)

__all__ = [
    "RESULT_COLUMNS",
    "AlphaEvaluator",
    "AverageAbsAlphaEvaluator",
    "CEQEvaluator",
    "CharBlock",
    "ClarkWestEvaluator",
    "CrossSectionView",
    "CrossSectionalR2Evaluator",
    "DataView",
    "Estimator",
    "Evaluator",
    "ExposureEvaluator",
    "FeatureBlock",
    "ForecastOutput",
    "ICEvaluator",
    "InformationRatioEvaluator",
    "M2Evaluator",
    "MeanReturnEvaluator",
    "Model",
    "OOSR2Evaluator",
    "OutOfSampleR2Evaluator",
    "PanelTensor",
    "PanelWeightsOutput",
    "PricingOutput",
    "RebalanceSchedule",
    "SharpeEvaluator",
    "SimulationResult",
    "SortResult",
    "SortinoEvaluator",
    "Splitter",
    "SquaredErrorDiffEvaluator",
    "StrategyReturnEvaluator",
    "SupportsForecast",
    "SupportsPricing",
    "SupportsWeights",
    "TimeSeriesView",
    "TreynorEvaluator",
    "VintagedBlock",
    "WalkForwardSplitter",
    "WeightsOutput",
    "adjust_pvalues",
    "adjust_tests",
    "alpha_regression",
    "available_evaluators",
    "backtest",
    "backtest_forecast",
    "backtest_panel",
    "backtest_pricing",
    "backtest_pricing_in_sample",
    "backtest_weights",
    "capabilities",
    "certainty_equivalent",
    "clark_west",
    "clark_west_test",
    "config_hash",
    "fama_macbeth",
    "get_evaluator",
    "grs_test",
    "make_sorts",
    "newey_west_lrv",
    "performance_fee",
    "pricing_in_sample",
    "register_evaluator",
    "return_loss",
    "sharpe_diff_test",
    "simulate_weights",
    "sort_portfolios",
    "validate_result",
    "validation_split",
    "walk_forward",
    "walk_forward_forecast",
    "walk_forward_panel",
    "walk_forward_pricing",
]
